Repository pierce-smith1/yok.scr, pull requests merged in 2024-04, with the labels that each got.

#59 Make palette customizer dialog not slow as shit
  Resource.rc
  configdialog.cpp
  configdialog.h
  palettes.cpp
  palettes.h
  resourcew.h
Labels: enhancement

#64 Minor color picker fixes
  configdialog.cpp
Labels: bug, enhancement

#56 Add palette sharing in the palette customizer
  Resource.rc
  configdialog.cpp
  configdialog.h
  palettes.h
  resourcew.h
Labels: bug, config

#57 PNG exporting for palettes
  Resource.rc
  configdialog.cpp
  configdialog.h
  graphics.cpp
  graphics.h
  resourcew.h
  yokscr.vcxproj
Labels: config

#69 Various palette customizer fixes
  Resource.rc
  configdialog.cpp
  palettes.cpp
Labels: bug, enhancement
